spring:
  db1:
    datasource:
      jdbc-url: jdbc:mysql://docker_batch_db:3306/r103?serverTimezone=Asia/Seoul
      username: user01
      password: user01
  db2:
    datasource:
      jdbc-url: jdbc:mysql://docker_batch_db:23306/r103?serverTimezone=Asia/Seoul
      username: user01
      password: user01